In [32]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import wordcloud 
import warnings
warnings.filterwarnings("ignore")

In [26]:
#Read the excel file and store the sheets into dataframes.
df = pd.ExcelFile(r"PythonHackathon/V02Max_Combined.xlsx")
kay = pd.read_excel(df, sheet_name = 'Kayaking')
ath = pd.read_excel(df, sheet_name = 'Athletes')
tri = pd.read_excel(df, sheet_name = 'Triathlon')
fen = pd.read_excel(df, sheet_name = 'Fencing')

## Qn1. Join all sport-related tables to produce one dataframe that has all athletes values. The final table should only have the same 5 columns: ID, time,power,RR, vo2, power. Write this dataframe to an excel file.


In [36]:
#Concatenating all sport related table to one dataframe final_table
final_table=pd.concat([fen[['ID','time','RR','VO2','power']],
                       kay[['ID','time','RR','VO2','power']],
                       tri[['ID','time','RR','VO2','power']]],ignore_index=True)

#defining output excel file name
output='FinalVO2_Table.xlsx'

#writing dataframe to excel using to_excel
final_table.to_excel(output,index=False)
print("Dataframe successfully written to Excel file",output)

#Reading the excel file back into dataframe for verification
print("\nReading",output,"Excel file for Verification:")
sportdf=pd.read_excel("FinalVO2_Table.xlsx")
print(sportdf)

Dataframe successfully written to Excel file FinalVO2_Table.xlsx

Reading FinalVO2_Table.xlsx Excel file for Verification:
       ID     time     RR       VO2  power
0       1 -130.840  672.0  0.302008      0
1       1 -130.168  672.0  0.302008      0
2       1 -129.536  632.0  0.301336      0
3       1 -128.824  712.0  0.301336      0
4       1 -127.948  876.0  0.301336      0
...    ..      ...    ...       ...    ...
52057  18  947.288  536.0  0.507071      0
52058  18  947.816  528.0  0.507071      0
52059  18  948.344  528.0  0.507071      0
52060  18  948.884  540.0  0.507071      0
52061  18  949.424  540.0  0.507071      0

[52062 rows x 5 columns]


## Qn2. Divide the rows into 3 parts: Warm up, GET(graded exercise test) and cool down using the data def. Label each row accordingly


In [30]:
#Initialize Dataframe phase
phase=pd.DataFrame(final_table)

#initialize Phase column
phase['Phase']='Other Phase'

#Apply conditions to find Warm Up-time less than 0,GET-time>=0 and power>0,Cool Down-time>0 and power=0
phase.loc[phase['time']<0,'Phase']='Warm Up'
phase.loc[(phase['time']>=0) & (phase['power']>0),'Phase']='GET'
phase.loc[(phase['time']>0) & (phase['power']==0),'Phase']='Cool Down'

#print dataframe phase details
print(phase)

       ID     time     RR       VO2  power      Phase
0       1 -130.840  672.0  0.302008      0    Warm Up
1       1 -130.168  672.0  0.302008      0    Warm Up
2       1 -129.536  632.0  0.301336      0    Warm Up
3       1 -128.824  712.0  0.301336      0    Warm Up
4       1 -127.948  876.0  0.301336      0    Warm Up
...    ..      ...    ...       ...    ...        ...
52057  18  947.288  536.0  0.507071      0  Cool Down
52058  18  947.816  528.0  0.507071      0  Cool Down
52059  18  948.344  528.0  0.507071      0  Cool Down
52060  18  948.884  540.0  0.507071      0  Cool Down
52061  18  949.424  540.0  0.507071      0  Cool Down

[52062 rows x 6 columns]


## Qn33. Create a list and a tuple. Print the types and lengths of both.


In [42]:
# Create a List and tuple
List=[1,2,3,4,5,6,7,8,9,10,11,12]
print(List)
tuple=(10,20,30,40,50,60,70,80,90,10,20)
print(tuple)

#Print the types of both.
print(type(list))
print(type(tuple))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
(10, 20, 30, 40, 50, 60, 70, 80, 90, 10, 20)
<class 'type'>
<class 'tuple'>


## Qn34. Display a word cloud using any values in the dataset



# Installing 

In [40]:
pip install wordcloud matplotlib

   ---------------------------------------- 0.0/301.4 kB ? eta -:--:--
   - -------------------------------------- 10.2/301.4 kB ? eta -:--:--
   ------------ --------------------------- 92.2/301.4 kB 1.3 MB/s eta 0:00:01
   ------------------------------- -------- 235.5/301.4 kB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 301.4/301.4 kB 1.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [42]:
from wordcloud import WordCloud

## Qn35. Create a Regression Plot on Max V02 and mean BMI for any sport of your choice
 

## Qn36. Plot the time series of HR( every 5 mins) of athlete 1


##Qn37. What was the maximum power achieved in terms of watts, which participant achieved it? Display name, sport and watts.


##Qn38.What is the average  difference in IBI during the warm up Vs the actual test?


##Qn39.Print out what's in indexes 7, 10, and 3 for the array. [1, 2, 3, 4, 5,6,7,8,9,10]


In [92]:
# define the array
array=[1,2,3,4,5,6,7,8,9,10]
indices=[7,10,3]
for index in indices:
    if index < len(array):
        print(f"Element at index {index}: {array[index]}")
    else:
        print(f"Index {index} is out of range.")


Check the index range
Element at index 7: 8
Index 10 is out of range.
Element at index 3: 4


##Qn40. "     [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]  Use array slicing to display elements 1,3,5. If the value is less than 4 display it as 99"


In [96]:
# Create the given array
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25],
                [26, 27, 28, 29, 30]])

# Slice the array to get elements 1, 3, and 5 (index 0, 2, and 4)
sliced = arr[:, [0, 2, 4]]

# Replace values less than 4 with 99
value = np.where(sliced < 4, 99, sliced)

print(value)


[[99 99  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]
 [26 28 30]]


##Qn41. What was lowest wattage achieved at the end of a test and by which participant? Display name, sport and watts.


##Qn42. What was the difference in heart rate between warm up and GET for athlete 1


##Qn43. Create a pivot table that shows count of patients within each age group and sport


##Qn44.Display a  distrubution chart of MAX V02 for all athletes


##n45. Create a dummy array with no data with a size of 15.


In [66]:
dummy_array = np.empty(15)

##Qn.46.How many minutes did participant 15s exercise last and what was the total V02 max consumed during the test?


##Qn47.Convert ' sport' into a numeric field through Label encoding


##Qn48. What was the average age of the athletes?


In [112]:
#Read the excel file and store the sheets into dataframes.
df = pd.ExcelFile(r"PythonHackathon/V02Max_Combined.xlsx")
ath = pd.read_excel(df, sheet_name = 'Athletes')

# Calculate the average age
average_age = ath['age'].mean()

print(f"Average age of athletes: {average_age:.2f} years")

Average age of athletes: 15.22 years
